# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build_and_test gh action workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@25316bbc1f10ac9d8798711f44914b1cf3c4e954 # v2.4.0
      with:
        cache: 'yarn'

    - run: yarn install
    - run: yarn run typecheck
    - run: yarn build
    - run: yarn lint
    - run: yarn test -w 2
